const SET_MY_TRACKS = 'SET_MY_TRACKS';
const ADD_MY_TRACK = 'ADD_MY_TRACK';
const TOGGLE_BOOKMARK = 'TOGGLE_BOOKMARK';
const DELETE_MY_TRACK = 'DELETE_MY_TRACK';

const SET_TRACK_FILTER = 'SET_TRACK_FILTER';
const SET_FOUND_TRACKS = 'SET_FOUND_TRACKS';
const ADD_FOUND_TRACKS = 'ADD_FOUND_TRACKS';

export default {
  SET_MY_TRACKS,
  ADD_MY_TRACK,
  TOGGLE_BOOKMARK,
  DELETE_MY_TRACK,
  SET_TRACK_FILTER,
  SET_FOUND_TRACKS,
  ADD_FOUND_TRACKS,
};
