const UPDATE_CHAT = 'UPDATE_CHAT';
const ADD_MESSAGE = 'ADD_MESSAGE';
const ADD_MESSAGES_TO_HEAD = 'ADD_MESSAGES_TO_HEAD';
const SET_CHAT_OFFSET = 'SET_CHAT_OFFSET';

export default {
  UPDATE_CHAT,
  ADD_MESSAGE,
  ADD_MESSAGES_TO_HEAD,
  SET_CHAT_OFFSET,
};
