import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  entryContainer: {
    margin: 10,
    // elevation: 200,
    backgroundColor: 'white',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.4,
    shadowRadius: 3,
    elevation: 5,
  },
  titleContainer: {
    borderRadius: 15,
    // borderTopRightRadius: 15,
    // borderTopLeftRadius: 15,
    padding: 10,
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    fontSize: 20,
    color: 'dodgerblue',
    flex: 8,
  },
  titleButtonContainer: {
    flex: 2,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  propRowContainer: {
    flexDirection: 'row',
  },
  propRowKey: {
    padding: 5,
    borderRadius: 10,
    color: 'dodgerblue',
    margin: 5,
  },
  propRowValue: {
    padding: 5,
    borderRadius: 10,
    margin: 5,
  },
  descContainer: {
    backgroundColor: 'rgba(250,250,250,1)',
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    padding: 5,
  },
  chevron: {
    padding: 5,
    color: 'dodgerblue',
    alignContent: 'center',
  },
  joinSchedule: {
    backgroundColor: 'dodgerblue',
    padding: 10,
    paddingHorizontal: 15,
    alignSelf: 'center',
    marginBottom: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
  cancel: {
    backgroundColor: 'firebrick',
    padding: 10,
    paddingHorizontal: 15,
    alignSelf: 'center',
    marginBottom: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
});
