import { StyleSheet, Dimensions } from 'react-native';

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    width: Dimensions.get('window').width - 40,
    height: Dimensions.get('window').height - 120,
    backgroundColor: 'white',
    margin: 20,
    elevation: 3,
    borderRadius: 10,
  },
  roof: {
    minHeight: 30,
    backgroundColor: '#2196f3',
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
  },
  infoWrapper: {
    flex: 1,
    justifyContent: 'space-between',
  },
  header: {
    flexDirection: 'row',
    marginVertical: 10,
  },
  titleIcon: {
    color: '#2196f3',
    marginRight: 5,
    borderRadius: 3,
    paddingTop: 10,
    paddingLeft: 5,
  },
  titleInputBox: {
    borderBottomColor: '#2196f3',
    borderBottomWidth: 1,
    height: 45,
    fontSize: 16,
  },
  pickerView: {
    flexDirection: 'row',
    marginTop: 10,
    marginLeft: 10,
  },
  pickerTitle: {
    backgroundColor: '#2196f3',
    color: 'white',
    padding: 5,
    alignItems: 'center',
    fontSize: 13,
    fontWeight: 'bold',
    borderRadius: 8,
  },
  picker: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#2196f3',
    marginLeft: 15,
  },
  pickerText: {
    padding: 5,
    marginHorizontal: 10,
  },
  icon: {
    width: 25,
    height: 25,
    marginTop: 2,
    marginRight: 10,
  },
  selectedTrack: {
    backgroundColor: '#e3dede',
    alignSelf: 'center',
    width: '100%',
    height: '100%',
  },
  unSelectedTrack: {
    backgroundColor: '#e3dede',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    height: '100%',
    width: '100%',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  trackButton: {
    borderRadius: 8,
    backgroundColor: '#2196f3',
    marginRight: 30,
    width: 100,
    height: 50,
    alignItems: 'center',
    alignContent: 'center',
  },
  submitButton: {
    borderRadius: 8,
    backgroundColor: '#03d6a7',
    marginLeft: 30,
    width: 100,
    height: 50,
    fontSize: 20,
    alignItems: 'center',
    alignContent: 'center',
  },
  timeInput: {
    marginLeft: 15,
    height: 30,
    alignSelf: 'center',
    padding: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#2196f3',
    textAlign: 'center',
  },
});

export default styles;
