import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  roof: {
    marginLeft: 20,
    marginTop: 20,
    height: 35,
    width: 370,
    backgroundColor: '#2196f3',
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
  },
  infoWrapper: {
    // borderBottomWidth: 1,
    elevation: 1,
    width: 370,
    marginLeft: 20,
    paddingBottom: 5,
    marginBottom: 10,
  },
  header: {
    flexDirection: 'row',
    width: 350,
    marginTop: 5,
  },
  titleIcon: {
    color: '#2196f3',
    marginRight: 5,
    borderRadius: 3,
    paddingTop: 10,
    paddingLeft: 5,
  },
  titleInputBox: {
    borderBottomColor: '#2196f3',
    borderBottomWidth: 1,
    width: 300,
    height: 45,
    fontSize: 16,
  },
  pickerView: {
    flexDirection: 'row',
    padding: 10,
    marginTop: 5,
    marginRight: 15,
    height: 50,
  },
  pickerTitle: {
    backgroundColor: '#2196f3',
    color: 'white',
    padding: 5,
    alignItems: 'center',
    fontSize: 13,
    fontWeight: 'bold',
    borderRadius: 8,
  },
  picker: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#2196f3',
    borderRadius: 8,
    width: 120,
    marginLeft: 15,
  },
  pickerText: {
    padding: 5,
    marginLeft: 10,
    width: 80,
  },
  icon: {
    width: 25,
    height: 25,
    marginTop: 2,
    marginRight: 10,
  },
  selectedTrack: {
    backgroundColor: '#e3dede',
    margin: 10,
    width: 300,
    height: 290,
    alignSelf: 'center',
  },
  unSelectedTrack: {
    backgroundColor: '#e3dede',
    margin: 30,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  trackButton: {
    borderRadius: 8,
    backgroundColor: '#2196f3',
    marginRight: 30,
    width: 100,
    height: 50,
    alignItems: 'center',
    alignContent: 'center',
  },
  submitButton: {
    borderRadius: 8,
    backgroundColor: '#03d6a7',
    marginLeft: 30,
    width: 100,
    height: 50,
    fontSize: 20,
    alignItems: 'center',
    alignContent: 'center',
  },
  timeInput: {
    marginLeft: 15,
    width: 100,
    height: 30,
    alignSelf: 'center',
    padding: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#2196f3',
  },
});

export default styles;
