import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  entryContainer: {
    margin: 10,
    // elevation: 200,
    backgroundColor: 'white',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.4,
    shadowRadius: 3,
    elevation: 5,
  },
  titleContainer: {
    padding: 10,
    paddingBottom: 1,
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  title: {
    paddingLeft: 7,
    paddingRight: 30,
    fontSize: 15,
    color: 'black',
    flex: 75,
    fontWeight: 'bold',
  },
  lengtgTitle: {
    fontSize: 15,
    color: '#03D6A7',
    flex: 30,
    fontWeight: 'bold',
  },
  titleButtonContainer: {
    flex: 25,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  propRowContainer: {
    flexDirection: 'row',
  },
  propRowKey: {
    padding: 5,
    borderRadius: 10,
    color: 'white',
    margin: 5,
  },
  propRowValue: {
    padding: 5,
    borderRadius: 10,
    margin: 5,
    marginLeft: 15,
  },
  descContainer: {
    backgroundColor: 'white',
    padding: 5,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  chevron: {
    padding: 5,
    alignContent: 'center',
  },
  delete: {
    padding: 10,
    backgroundColor: '#ef3832',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 10,
    marginBottom: 10,
  },
  showDetail: {
    padding: 10,
    borderColor: '#03D6A7',
    backgroundColor: '#03D6A7',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 10,
    marginBottom: 10,
  },
});
